name: release_major
on: workflow_dispatch

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
jobs:
  bumb_version:
    runs-on: ubuntu_latest
    steps:
    - uses: actions/checkout@v2
    - name: Update git tag version 
      working-directory: ${{github.workspace}}/TextEditor
      run: cmake -DBUMB_VERSION=MAJOR -P BumbVersion.cmake